### ISSUE TITLE
Hi, can this library be used just to get layout coordinates given a dependency graph, which I want to use to layout in a different front end setup?

### ISSUE THREAD

**Issue by shivam529** [tomnelson/jungrapht-visualization#22]

**Comment by tomnelson** [comment]
You can use the code in the jungrapht-layout jar to apply layout algorithms, then retrieve the Points from the LayoutModel.

**Comment by tomnelson** [comment]
Here is an example:


        Graph<String, Integer> graph =
                GraphTypeBuilder.<String, Integer>forGraphType(DefaultGraphType.dag())
                        .edgeSupplier(SupplierUtil.createIntegerSupplier())
                        .allowingSelfLoops(true)
                        .buildGraph();
        IntStream.range(0, 10)
                .forEach(
                        i -> {
                            graph.addVertex("A" + i);
                            graph.addVertex("B" + i);
                            graph.addVertex("C" + i);
                            graph.addEdge("A" + i, "B" + i);
                            graph.addEdge("A" + i, "C" + i);
                        });

        TidierTreeLayoutAlgorithm<String, Integer> layoutAlgorithm =
                TidierTreeLayoutAlgorithm.<String, Integer>edgeAwareBuilder().expandLayout(false).build();
        LayoutModel<String> layoutModel = LayoutModel.<String>builder().size(100, 100).graph(graph).build();
        layoutAlgorithm.visit(layoutModel);

        System.out.println("points are "+layoutModel.getLocations());
