### ISSUE TITLE
Left -> Right Tree Layout

### ISSUE THREAD

**Issue by io7m** [tomnelson/jungrapht-visualization#24]
Hello!

Is there a way to get tree layouts to be laid out left-to-right instead of top-to-bottom?

Something along the lines of:

https://graphviz.org/Gallery/directed/ninja.svg

**Comment by tomnelson** [comment]
Thanks for your interest!
There are 2 demos:

L2RTreeLayoutDemo
TidierL2RTreeLayoutDemo

The code that maps the layout L2R is this:

    vv.getVisualizationModel()
        .getLayoutModel()
        .getLayoutStateChangeSupport()
        .addLayoutStateChangeListener(
            evt -> {
              if (!evt.active) {
                LayoutModel<String> layoutModel = evt.layoutModel;
                layoutModel
                    .getLocations()
                    .forEach(
                        (v, p) -> layoutModel.set(v, Point.of(p.y, layoutModel.getWidth() - p.x)));
              }
            });


If you want to go from right to left, like your example image, change it like this:
                    .forEach(
                        (v, p) -> layoutModel.set(v, Point.of(
                                layoutModel.getHeight() - p.y,  p.x)));

**Comment by io7m** [comment]
Ah, thanks, I'll give it a try!

I've been unable to get any of the demo code to run as the latest Intellij IDEA seems to have serious problems opening the project. For whatever reason, it consistently manages to open the modules in a broken state.

**Comment by tomnelson** [comment]
I use Intellij IDEA for development, so I run the demos with it all the time. 
I just downloaded the latest version (2022.3.2) and did not have any problems.

To test it everything, I did this:

  git clone git@github.com:tomnelson/jungrapht-visualization.git
  cd jungrapht-visualization
  mvn clean install
  

After building it, I used File -> Open
and made a new project like this:
<img width="697" alt="image" src="https://user-images.githubusercontent.com/105223/215352358-082afbb9-eae8-48d9-ad99-229470bbecdf.png">

**Comment by io7m** [comment]
Following those exact steps, I get a project that has no Maven modules and no source directories configured:

![ide](https://user-images.githubusercontent.com/612494/215353234-4d0cf73f-1cda-4f85-92ed-2e012c576d67.png)

It's possible to go through and manually set source directories, but notice that it also fails to include any Maven dependencies, and even the "Repair IDE..." option that takes me through a ton of steps to clear indices, reindex, etc, fails in the end.

![ide2](https://user-images.githubusercontent.com/612494/215353236-07c99440-0323-42b6-abce-2364e3e242bc.png)

I've not seen this happen with a Maven project before.

**Comment by io7m** [comment]
Checking to see if this is still the case on the latest version... :hourglass:

**Comment by tomnelson** [comment]
Mine looks like this, in the maven panel:
<img width="416" alt="image" src="https://user-images.githubusercontent.com/105223/215353743-284b9e33-81d7-49e6-b7b9-a0e991652302.png">

You might try invalidating the caches and loading the project again. I can't think of any other things to try.

**Comment by io7m** [comment]
It appears it was a bug with the `2022.2.4` version. It imports fine with `2022.3.2`. Sorry for the noise!

**Comment by tomnelson** [comment]
Glad you found a solution.
For that its worth, your question led me to think of a way to change the layout direction within the 
jungrapht-layout module.  I want the layouts to be independent of the visualization layer and any awt classes, so the layouts can be used with a different rendering system.

The layout algorithms can take an 'after' function (a Runnable) that runs when they are done.
I pushed some changes to the master branch. I think this approach is better.

**Comment by tomnelson** [comment]
I don't have a layout algorithm that would produce that output. If I had an Orthogonal layout algorithm, it could be close, but you need to make some placement decisions based on the types of the endpoints.

This is the closest I could get, using the EiglspergerLayoutAlgorithm and rotating it:

<img width="925" alt="image" src="https://user-images.githubusercontent.com/105223/215499792-fcf68af8-4192-49a7-8992-8c4d2dc67667.png">

**Comment by tomnelson** [comment]
If you want to see your graph with many different layouts, I pushed a demo called  ShowLayoutsWithIO7MGraph to the master branch.
