### ISSUE TITLE
addGraphMouseListener does not fire after panning/zooming.

### ISSUE THREAD

**Issue by mku11** [tomnelson/jungrapht-visualization#28]
After panning or zooming clicking on a vertex addGraphMouseListener does not fire the listener. It seems that the vertex positions are not recalculated correctly because SpatialRTree.recalculate() sets the same old positions.

I'm not sure if I'm missing something else., I'm running sample VisualizationScrollPaneDemo.

**Comment by tomnelson** [comment]
Thank you for using jungrapht and reporting this. 
I fixed MouseListenerTranslator, and I believe it fixed this problem and pushed the new code.

**Comment by mku11** [comment]
Thanks, I got your fix and it works!

**Comment by tomnelson** [comment]
Thanks for confirming!
