### ISSUE TITLE
Add Getter for mass in org.jungrapht.visualization.layout.quadtree.ForceObject

### ISSUE THREAD

**Issue by SemyonSinchenko** [tomnelson/jungrapht-visualization#6]
Hello!
Thank you for this nice library!

Can you please add a Getter for a mass (or make it public) in ForceObject?
I need it for implement a ForceAtlas2 (like in Gephi) because they use a "Repulsion by degree" conception and mass of objects (aka degree) must be used in implementation of ForceObject.addForceFrom method: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0098679

Many thanks in advance!

**Comment by tomnelson** [comment]
Done! Thanks for your interest.
